FROM denoland/deno:2.2.6

# Install CA certificates for local development
RUN apt-get update && apt-get install -y ca-certificates

WORKDIR /app

COPY deno.json .

RUN deno install

COPY . .

RUN deno cache main.ts

RUN deno task build

# open port 8000 when running the container. (-p 8000:8000)
ARG PORT=8000
EXPOSE $PORT

# build the app and serve the main.ts file.
CMD ["deno", "task", "serve"]