// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_lang_index from "./routes/[lang]/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_citation_images from "./routes/admin/citation-images.tsx";
import * as $admin_entity_images from "./routes/admin/entity-images.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $api_middleware from "./routes/api/_middleware.ts";
import * as $api_articles_manual_generate_index from "./routes/api/articles/manual-generate/index.ts";
import * as $api_articles_thumbnail from "./routes/api/articles/thumbnail.ts";
import * as $api_image_search_index from "./routes/api/image-search/index.ts";
import * as $api_scrape_article_extractor_index from "./routes/api/scrape/article-extractor/index.ts";
import * as $api_test from "./routes/api/test.ts";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $articles_article_row from "./islands/articles/article-row.tsx";
import * as $articles_article_viewer from "./islands/articles/article-viewer.tsx";
import * as $articles_citation_article_row from "./islands/articles/citation-article-row.tsx";
import * as $articles_thumbnail_candidate from "./islands/articles/thumbnail-candidate.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[lang]/index.tsx": $_lang_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/citation-images.tsx": $admin_citation_images,
    "./routes/admin/entity-images.tsx": $admin_entity_images,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/api/_middleware.ts": $api_middleware,
    "./routes/api/articles/manual-generate/index.ts":
      $api_articles_manual_generate_index,
    "./routes/api/articles/thumbnail.ts": $api_articles_thumbnail,
    "./routes/api/image-search/index.ts": $api_image_search_index,
    "./routes/api/scrape/article-extractor/index.ts":
      $api_scrape_article_extractor_index,
    "./routes/api/test.ts": $api_test,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/articles/article-row.tsx": $articles_article_row,
    "./islands/articles/article-viewer.tsx": $articles_article_viewer,
    "./islands/articles/citation-article-row.tsx":
      $articles_citation_article_row,
    "./islands/articles/thumbnail-candidate.tsx": $articles_thumbnail_candidate,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
